#!/usr/bin/env bash

set -euo pipefail

docker() {
    if command -V docker &>/dev/null; then
        command docker "$@"
    elif command -V podman &>/dev/null; then
        podman "$@"
    else
        echo "Could not find docker or podman" >&2
        exit 1
    fi
}

here=$(cd "$(dirname "$0")" && pwd)
repo_root="$(cd "$here/.." && pwd)"
repo_name="$(basename "$repo_root")"

cd "$here"
img_id="$(echo "Building docker image..." >&2 && docker build -q .)"

run_args=(--entrypoint bash)
run_args+=(--rm)
run_args+=(--volume "$repo_root":"/$repo_name")
run_args+=(--workdir "/$repo_name")
run_args+=(--interactive)

if test -t 0; then
    run_args+=(--tty)
fi

exec docker run "${run_args[@]}" "$img_id" "$@"
