#!/usr/bin/env bash

set -euo pipefail

container_engine="$(
    for engine in docker podman; do command -v "$engine" && exit 0; done
    echo "Could not find supported container engine." >&2 && exit 1
)"

here=$(cd "$(dirname "$0")" && pwd)
repo_root="$(cd "$here/.." && pwd)"
repo_name="$(basename "$repo_root")"

cd "$here"
img_id="$(echo "Building docker image..." >&2 && "$container_engine" build -q .)"

run_args=(--entrypoint bash)
run_args+=(--rm)
run_args+=(--volume "$repo_root":"/$repo_name")
run_args+=(--workdir "/$repo_name")
run_args+=(--interactive)

if test -t 0; then
    run_args+=(--tty)
fi

exec "$container_engine" run "${run_args[@]}" "$img_id" "$@"
